### ISSUE TITLE
dbplyr compatiblity

### ISSUE THREAD

**Issue by cwolfsonseeley** [tarakc02/listbuilder#5]
As reported by Ellen Kamoe (and reproduced by myself), installation of listbuilder fails with the following error message: "Error : object 'src_desc' is not exported by 'namespace:dplyr'".

My research suggests this is an issue because in dplyr 0.6.0, a number of database and sql functions moved from dplyr to dbplyr. 

I attempted to add code to solve the issue, but I do not have permission to push my code to the git repository. So I am creating an issue for review by TS.

See check_dbplyr() and wrap_dbplyr_obj(obj_name).

**Comment by tarakc02** [comment]
I've already communicated with CWS, but posting here to say that I've updated both `listbuilder` and `discoveryengine` so that they should work (for now). The originally identified problem is in `getcdw`, and I've (for now) disabled the problematic feature while I do more research. That means that as of now, everything "works" in the sense that everything can be installed and used, but the `dplyr` functionality that was part of `getcdw` is currently disabled. I'm reviewing the documentation for `dbplyr` and will be re-implementing the dplyr functionality, which I think will come in handy.
